name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    env:
      DB_DATABASE: improveyou_inf20s
      DB_USERNAME: data_exchange
      DB_PASSWORD: sml@12345!
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '8.0'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: cp .env.example .env
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress --no-scripts
      - name: Generate key
        run: php artisan key:generate
      - name: Set up MySQL
        run: |
          sudo service mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USERNAME -p$DB_PASSWORD
      - name: Run database migrations
        run: php artisan migrate --force
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
