name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
        - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
          
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2.5'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: cp .env.example .env
      - name: Install Composer
        run: composer install 
      - name: Install NodeModules
        run: npm install
      - name: Generate key
        run: php artisan key:generate
      - name: Create Link btw public and storage folder
        run: php artisan storage:link
      - name: Run database migrations
        env:
          DB_HOST: mysql
        run: php artisan migrate
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: |
          vendor/phpunit/phpunit/phpunit
